### ISSUE TITLE
Shared app/resources folder for ember/rails projects, this would allow the very effective creation of crud apps

### ISSUE THREAD

**Issue by ghost** [hhff/donut#3]
For example resources/user/config.yaml

config.yaml could be as minimal as:

```yaml
name: Todo
fields:
  name: string
  is_done: boolean
```

At the moment im leaning towards reading this file in at runtime in both rails and ember in order to avoid nasty code generation.

Both ember and rails implementation should be easily through the conventional patterns.
